site_name: "Wiki"
site_description: EAxWiki — EA model wiki
docs_dir: wiki
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

use_directory_urls: false

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.highlight

extra_css:
  - extra.css

extra_javascript:
  - cytoscape.min.js
  - graph-init.js
  - status-editor.js

plugins:
  - search
  - awesome-pages
  - glightbox

# If you want an explicit navigation order, uncomment and adjust 'nav'
# nav:
#   - Home: index.md
#   - Architecture:
#     - Overview: Architecture/index.md
