using EAxWiki.Monitor;

namespace EAxWiki.Tests;

public class IdempotentWriterTests : IDisposable
{
    private readonly string _dir;
    private readonly string _path;

    public IdempotentWriterTests()
    {
        _dir = Path.Combine(Path.GetTempPath(), "eaxwiki_idem_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_dir);
        _path = Path.Combine(_dir, "page.md");
    }

    public void Dispose()
    {
        if (Directory.Exists(_dir)) Directory.Delete(_dir, recursive: true);
    }

    [Fact]
    public void CreatesFile_WhenMissing()
    {
        IdempotentWriter.WriteIfChanged(_path, "hello");
        Assert.Equal("hello", File.ReadAllText(_path));
    }

    [Fact]
    public void PreservesMtime_WhenContentIdentical()
    {
        File.WriteAllText(_path, "hello");
        var mtimeBefore = File.GetLastWriteTimeUtc(_path);
        Thread.Sleep(50);

        IdempotentWriter.WriteIfChanged(_path, "hello");

        Assert.Equal(mtimeBefore, File.GetLastWriteTimeUtc(_path));
    }

    [Fact]
    public void PreservesMtime_WhenOnlyTimestampLineDiffers()
    {
        // This is the whole point: monitor cycles every 30s rewriting a "Generated at HH:mm:ss"
        // line into an otherwise-unchanged page. Without masking, mkdocs livereload fires on
        // every tick and yanks the browser back to the top.
        File.WriteAllText(_path, "# Errors\n\n*Generated by EAxWiki.Monitor - foo. Last checked 2026-09-09 10:00:00.*\n\nNo issues.\n");
        var mtimeBefore = File.GetLastWriteTimeUtc(_path);
        Thread.Sleep(50);

        IdempotentWriter.WriteIfChanged(_path, "# Errors\n\n*Generated by EAxWiki.Monitor - foo. Last checked 2026-09-09 10:00:30.*\n\nNo issues.\n");

        Assert.Equal(mtimeBefore, File.GetLastWriteTimeUtc(_path));
    }

    [Fact]
    public void HealthPage_IdenticalContent_KeepsMtime()
    {
        // Regression: HealthPageRenderer used to call File.WriteAllText unconditionally,
        // bumping mtime every 30-second check cycle even when the rendered content was
        // byte-identical. mkdocs livereload watches mtime, not content, so every reader's
        // page snapped back to the top on a 30-second beat.
        var content = "# Pipeline Health\n\n- Overall: Healthy\n- Exit code: 0\n";
        File.WriteAllText(_path, content);
        var mtimeBefore = File.GetLastWriteTimeUtc(_path);
        Thread.Sleep(50);

        IdempotentWriter.WriteIfChanged(_path, content);

        Assert.Equal(mtimeBefore, File.GetLastWriteTimeUtc(_path));
    }

    [Fact]
    public void Writes_WhenMeaningfulContentDiffers()
    {
        File.WriteAllText(_path, "# Errors\n\n*Generated by EAxWiki.Monitor - foo. Last checked 2026-09-09 10:00:00.*\n\nNo issues.\n");
        Thread.Sleep(50);

        IdempotentWriter.WriteIfChanged(_path, "# Errors\n\n*Generated by EAxWiki.Monitor - foo. Last checked 2026-09-09 10:00:00.*\n\n- New error!\n");

        Assert.Contains("New error!", File.ReadAllText(_path));
    }
}
