using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace EAxWiki.Monitor;

/// <summary>
/// Renders {wikiDir}/status/config.md (fully code-generated — no template): resolved
/// MonitorOptions with secrets masked, alert destinations as configured/not-configured, and the
/// cached scheduled-task snapshot. Read-only; never contains webhook URLs, tokens, or keys.
/// </summary>
public class ConfigPageRenderer
{
    private static readonly Regex ConnectionStringRegex = new(@"(?i)(Password|Pwd)\s*=[^;]*", RegexOptions.Compiled);

    private readonly string _outputPath;
    private readonly IScheduledTaskSnapshot _schedule;

    public ConfigPageRenderer(string wikiDir, IScheduledTaskSnapshot schedule)
    {
        _outputPath = Path.Combine(wikiDir, "status", "config.md");
        _schedule = schedule;
    }

    public void Render(MonitorOptions options, DateTime now)
    {
        var schedule = _schedule.Get();
        var sb = new StringBuilder();
        sb.AppendLine("# Configuration");
        sb.AppendLine();
        sb.AppendLine($"*Generated by EAxWiki.Monitor at {now.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture)} - current resolved runtime configuration, read-only.*");
        sb.AppendLine();
        sb.AppendLine("## Run settings");
        sb.AppendLine();
        sb.AppendLine("| Setting | Value |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| Wiki dir | `{options.WikiDir}` |");
        sb.AppendLine($"| Repository | `{RedactRepo(options.RepoPath)}` |");
        sb.AppendLine($"| Wiki port | {options.WikiPort} |");
        sb.AppendLine($"| API port | {options.ApiPort} |");
        sb.AppendLine($"| LLM port | {options.LlmPort} |");
        sb.AppendLine($"| Export interval | {options.ExportIntervalMinutes} min |");
        sb.AppendLine($"| Check interval | {options.CheckIntervalSeconds} s |");
        sb.AppendLine($"| Max retries | {options.MaxRetries} |");
        sb.AppendLine($"| Retry delay | {options.RetryDelaySeconds} s |");
        sb.AppendLine($"| Min element fraction | {options.MinElementFraction.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| Force | {(options.Force ? "enabled" : "disabled")} |");
        sb.AppendLine($"| Force every N runs | {(options.ForceEveryNRuns == 0 ? "off" : $"every {options.ForceEveryNRuns} runs")} |");
        sb.AppendLine($"| AI mode | {options.AiMode} |");
        sb.AppendLine($"| AI endpoint | {options.AiEndpoint ?? "(not set)"} |");
        sb.AppendLine($"| AI model | {options.AiModel ?? "(not set)"} |");
        sb.AppendLine();
        sb.AppendLine("## Alert destinations");
        sb.AppendLine();
        sb.AppendLine("| Destination | Status |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| Slack | {(string.IsNullOrEmpty(options.WebhookUrl) ? "not configured" : "configured")} |");
        sb.AppendLine($"| Teams | {(string.IsNullOrEmpty(options.TeamsWebhookUrl) ? "not configured" : "configured")} |");
        sb.AppendLine($"| Telegram | {(string.IsNullOrEmpty(options.TelegramBotToken) ? "not configured" : "configured")} |");
        sb.AppendLine();
        sb.AppendLine("## Schedule");
        sb.AppendLine();
        if (schedule == null)
        {
            sb.AppendLine("Schedule info unavailable (the scheduled task could not be queried).");
        }
        else
        {
            sb.AppendLine("| Field | Value |");
            sb.AppendLine("|---|---|");
            sb.AppendLine($"| Task name | `{schedule.TaskName}` |");
            sb.AppendLine($"| State | {schedule.State} |");
            sb.AppendLine($"| Wake to run | {(schedule.WakeToRun ? "enabled" : "disabled")} |");
            sb.AppendLine($"| Execution time limit | {schedule.ExecutionTimeLimit} |");
            sb.AppendLine($"| Multiple instances | {schedule.MultipleInstances} |");
            sb.AppendLine();
            sb.AppendLine("### Triggers");
            sb.AppendLine();
            foreach (var trigger in schedule.Triggers)
                sb.AppendLine($"- {trigger}");
        }

        Directory.CreateDirectory(Path.GetDirectoryName(_outputPath)!);
        File.WriteAllText(_outputPath, sb.ToString());
    }

    private static string RedactRepo(string? value)
    {
        if (string.IsNullOrEmpty(value)) return "(not set)";
        return ConnectionStringRegex.Replace(value, "$1=***");
    }
}