using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using EAxWiki.Export.Helpers;

namespace EAxWiki.Monitor;

/// <summary>
/// Renders {wikiDir}/status/config.md (fully code-generated — no template): resolved
/// MonitorOptions with secrets masked, alert destinations as configured/not-configured, and the
/// cached scheduled-task snapshot. Read-only for the operational bits at the top; a brand-editor
/// widget shell (issue #98) is injected at the bottom so users can tint their wiki without hand-
/// editing brand.css.
/// </summary>
public class ConfigPageRenderer
{
    private static readonly Regex ConnectionStringRegex = new(@"(?i)(Password|Pwd)\s*=[^;]*", RegexOptions.Compiled);

    private readonly string _wikiDir;
    private readonly string _outputPath;
    private readonly IScheduledTaskSnapshot _schedule;

    public ConfigPageRenderer(string wikiDir, IScheduledTaskSnapshot schedule)
    {
        _wikiDir = wikiDir;
        _outputPath = Path.Combine(wikiDir, "status", "config.md");
        _schedule = schedule;
    }

    public void Render(MonitorOptions options, DateTime now)
    {
        var schedule = _schedule.Get();
        var sb = new StringBuilder();
        sb.AppendLine("# Configuration");
        sb.AppendLine();
        sb.AppendLine($"*Generated by EAxWiki.Monitor at {now.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture)} - current resolved runtime configuration, read-only.*");
        sb.AppendLine();
        sb.AppendLine("## Run settings");
        sb.AppendLine();
        sb.AppendLine("| Setting | Value |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| Wiki dir | `{options.WikiDir}` |");
        sb.AppendLine($"| Repository | `{RedactRepo(options.RepoPath)}` |");
        sb.AppendLine($"| Wiki port | {options.WikiPort} |");
        sb.AppendLine($"| API port | {options.ApiPort} |");
        sb.AppendLine($"| LLM port | {options.LlmPort} |");
        sb.AppendLine($"| Export interval | {options.ExportIntervalMinutes} min |");
        sb.AppendLine($"| Check interval | {options.CheckIntervalSeconds} s |");
        sb.AppendLine($"| Max retries | {options.MaxRetries} |");
        sb.AppendLine($"| Retry delay | {options.RetryDelaySeconds} s |");
        sb.AppendLine($"| Min element fraction | {options.MinElementFraction.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| Force | {(options.Force ? "enabled" : "disabled")} |");
        sb.AppendLine($"| Force every N runs | {(options.ForceEveryNRuns == 0 ? "off" : $"every {options.ForceEveryNRuns} runs")} |");
        sb.AppendLine($"| AI mode | {options.AiMode} |");
        sb.AppendLine($"| AI endpoint | {options.AiEndpoint ?? "(not set)"} |");
        sb.AppendLine($"| AI model | {options.AiModel ?? "(not set)"} |");
        sb.AppendLine();
        sb.AppendLine("## Alert destinations");
        sb.AppendLine();
        sb.AppendLine("| Destination | Status |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| Slack | {(string.IsNullOrEmpty(options.WebhookUrl) ? "not configured" : "configured")} |");
        sb.AppendLine($"| Teams | {(string.IsNullOrEmpty(options.TeamsWebhookUrl) ? "not configured" : "configured")} |");
        sb.AppendLine($"| Telegram | {(string.IsNullOrEmpty(options.TelegramBotToken) ? "not configured" : "configured")} |");
        sb.AppendLine();
        sb.AppendLine("## Schedule");
        sb.AppendLine();
        if (schedule == null)
        {
            sb.AppendLine("Schedule info unavailable (the scheduled task could not be queried).");
        }
        else
        {
            sb.AppendLine("| Field | Value |");
            sb.AppendLine("|---|---|");
            sb.AppendLine($"| Task name | `{schedule.TaskName}` |");
            sb.AppendLine($"| State | {schedule.State} |");
            sb.AppendLine($"| Wake to run | {(schedule.WakeToRun ? "enabled" : "disabled")} |");
            sb.AppendLine($"| Execution time limit | {schedule.ExecutionTimeLimit} |");
            sb.AppendLine($"| Multiple instances | {schedule.MultipleInstances} |");
            sb.AppendLine();
            sb.AppendLine("### Triggers");
            sb.AppendLine();
            foreach (var trigger in schedule.Triggers)
                sb.AppendLine($"- {trigger}");
        }

        AppendBrandEditor(sb, options);

        Directory.CreateDirectory(Path.GetDirectoryName(_outputPath)!);
        File.WriteAllText(_outputPath, sb.ToString());
    }

    // Emits the shell for brand-editor.js (issue #98) below the read-only status tables. Seeded
    // with the current brand.css body and the current mkdocs.yml logo path so the widget can boot
    // the pickers to the right values. The token is read once at render time — same
    // ApiTokenStore that the other editors already publish to widgets in exported pages.
    private void AppendBrandEditor(StringBuilder sb, MonitorOptions options)
    {
        var brandCssPath = Path.Combine(_wikiDir, "brand.css");
        var brandCss = File.Exists(brandCssPath) ? File.ReadAllText(brandCssPath) : "";

        string? currentLogo = null;
        try
        {
            var mkdocsPath = Path.Combine(AppContext.BaseDirectory, "mkdocs.yml");
            if (!File.Exists(mkdocsPath))
                mkdocsPath = Path.Combine(Directory.GetCurrentDirectory(), "mkdocs.yml");
            if (File.Exists(mkdocsPath))
                currentLogo = MkdocsYmlProbe.GetLogo(mkdocsPath);
        }
        catch { /* best-effort — widget still renders without a logo preview */ }

        string token;
        try { token = ApiTokenStore.GetOrCreate(_wikiDir); }
        catch { token = ""; }

        sb.AppendLine();
        sb.AppendLine("## Brand");
        sb.AppendLine();
        sb.AppendLine("Color, font, and logo — saved to `wiki/brand.css` (and `mkdocs.yml` for the logo). Changes take effect on the next page reload; a logo change requires restarting the wiki serve.");
        sb.AppendLine();

        sb.Append("<div id=\"ea-brand-editor\"");
        sb.Append(" data-api-port=\"").Append(options.ApiPort).Append('"');
        sb.Append(" data-api-token=\"").Append(HtmlAttrEscape(token)).Append('"');
        sb.Append(" data-current-logo=\"").Append(HtmlAttrEscape(currentLogo ?? "")).Append('"');
        sb.Append(" data-brand-css=\"").Append(HtmlAttrEscape(brandCss)).Append('"');
        sb.AppendLine("></div>");
    }

    private static string HtmlAttrEscape(string s) =>
        s.Replace("&", "&amp;").Replace("\"", "&quot;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static string RedactRepo(string? value)
    {
        if (string.IsNullOrEmpty(value)) return "(not set)";
        return ConnectionStringRegex.Replace(value, "$1=***");
    }
}

// Monitor doesn't have InternalsVisibleTo for EAxWiki, so we duplicate the tiny logo-line
// read here. Kept package-private and only used by ConfigPageRenderer's best-effort preview.
internal static class MkdocsYmlProbe
{
    public static string? GetLogo(string path)
    {
        var lines = File.ReadAllLines(path);
        int themeStart = -1;
        for (int i = 0; i < lines.Length; i++)
        {
            if (lines[i].StartsWith("theme:"))
            {
                themeStart = i;
                break;
            }
        }
        if (themeStart < 0) return null;
        for (int i = themeStart + 1; i < lines.Length; i++)
        {
            var line = lines[i];
            if (line.Length == 0) continue;
            var trimmed = line.TrimStart();
            if (trimmed.StartsWith('#')) continue;
            if (line[0] != ' ' && line[0] != '\t') break;
            if (trimmed.StartsWith("logo:"))
            {
                var colon = line.IndexOf(':');
                return colon < 0 ? null : line[(colon + 1)..].Trim();
            }
        }
        return null;
    }
}
