using System.Text.RegularExpressions;

namespace EAxWiki.Monitor;

/// <summary>
/// Writes status pages only when meaningful content changed. Without this, the Monitor's
/// 30-second check cycle rewrites <c>errors.md</c> / <c>config.md</c> with a fresh
/// "Generated at HH:mm:ss" line every tick — mkdocs sees the file mtime change and triggers
/// a livereload, which yanks the browser back to the top of whatever page the user is
/// reading (issue: "page refreshes every so often, looks silly").
///
/// The `*Generated by ... *` line is masked before comparison so a timestamp-only
/// difference is treated as no change. Everything else is compared byte-for-byte.
/// </summary>
public static class IdempotentWriter
{
    private static readonly Regex GeneratedLinePattern =
        new(@"\*Generated by[^\r\n]*\*", RegexOptions.Compiled);

    public static void WriteIfChanged(string path, string content)
    {
        if (File.Exists(path))
        {
            var existing = File.ReadAllText(path);
            if (Normalize(existing) == Normalize(content)) return;
        }
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
    }

    private static string Normalize(string s) => GeneratedLinePattern.Replace(s, "");
}
